db.define_table('resume_info',
  Field('user_id', db.auth_user),
  Field('sector', type='text'),
  Field('job_position', type='text'),
  Field('department', type='text'),
  Field('period_from', type='text'),
  Field('period_to', type='text'),
  Field('responsibilities', type='text'),
  Field('course', type='text'),
  Field('project', type='text'),
  Field('education_degree', type='text'),
  Field('certificate', type='text'),
  Field('award', type='text'),
  Field('volunteer', type='text'),
  Field('technical_skills', type='text'),
  Field('language_proficiency', type='text'),
  Field('request_status', type='string',
    requires=IS_IN_SET(['pending', 'acknowledged', 'finish'])),
  migrate=True
)
